# Generated by Django 4.0.4 on 2022-05-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_post_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post',
            new_name='post_body',
        ),
    ]
